### ISSUE TITLE
Atom installs its own tern

### ISSUE THREAD

**Issue by jpenninkhof** [TimoSta/tern-openui5#5]
The setup section in the readme mentions that you'll have to install Tern and copy openui5.js to the plugins directory. However, atom-ternjs installs its own version of Tern. It is not necessary to install it seperately. The openui5.js should obsviously still be copied, but to a tern/plugins directory under the users' ~/.atom directory.

**Comment by TimoStaudinger** [comment]
You are absolutely right.

What the readme is trying to say is that you need to install Tern, one way or another. The Atom specific section is simply suggesting a way how to easily get a Tern installation that integrates well with Atom.

I can see how the current description is confusing, though -- I will have another look at it over the next few days and try to find a better way to phrase it.

**Comment by jpenninkhof** [comment]
Thanks for looking into this Timo. You’re right, It put me on the wrong leg as I am (was) not familiar with Tern. Do let me know if you’re open for a contribution in this area. I don’t mind putting my copywriting skills to a test ;)

Perhaps a bit off-topic: I also noticed that the webcrawler currently breaks on a documentation page in which > and < characters weren’t encoded properly. In order to fix it in the crawler, I’m afraid it would be
necessary to open the bonnet of cheerio. Instead, I have asked SAP to look into the page and hope they’ll fix the invalid html-encoding on that page: https://github.com/SAP/openui5/issues/875

Excellent initiative Timo! Love it!

Cheers,
Jan

**Comment by TimoStaudinger** [comment]
Feel free to contribute to this project -- I would love to make this a community effort! It's great to see that I'm not the only one using this plugin. :)

Regarding your second point, I haven't even noticed that one yet.
I opened issue #6 for it to keep it separate from this documentation issue.

Thanks!
Timo

**Comment by TimoStaudinger** [comment]
@jpenninkhof I had a go at the docs, hope that clarifies things a bit.

I also described how to install the plugin in Atom directly via npm, getting rid of the copy-paste magic. :-)
